name: Inputs

on:
  workflow_dispatch:
    inputs:

      username:
        description: "Enter your name"
        required: true
        default: "DevOps Engineer"
        type: string

      environment:
        description: "Select environment"
        required: true
        type: environment

      deploy:
        description: "Do you want to deploy?"
        required: true
        type: boolean
        default: false

      log_level:
        description: "Choose log level"
        required: true
        type: choice
        default: info
        options:
          - info
          - warn
          - error

      retry_count:
        description: "Retry Count"
        required: false
        type: number
        default: 3

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Print user inputs
        run: |
          echo "Username: ${{ inputs.username }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Deploy: ${{ inputs.deploy }}"
          echo "Log Level: ${{ inputs.log_level }}"
          echo "Retry Count: ${{ inputs.retry_count }}"