name: Context demo

on:
  workflow_dispatch:

env:
  APP_NAME: demo-app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Contexts
        run: |
          echo "Repository : ${{ github.repository }}"
          echo "Actor      : ${{ github.actor }}"
          echo "Branch     : ${{ github.ref_name }}"
          echo "OS          : ${{ runner.os }}"
          echo "App Name    : ${{ env.APP_NAME }}"